version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG_FILE: ".env"
    entrypoint:
      sh -c "
      cd corp_staff &&
      
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
          condition: service_healthy
    networks:
      - web_net

  db:
    container_name: main_db
    image: postgres:15.1-alpine
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      CONFIG_FILE: ".env"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - web_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 10s
      retries: 30

networks:
  web_net:
    name: web_net
